/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author lupita
 */
public class View_Edad extends javax.swing.JFrame {

    /**
     * Creates new form View_Edad
     */
    public View_Edad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Año_nac = new javax.swing.JLabel();
        jtf_Año_nac = new javax.swing.JTextField();
        jbtn_Verificar = new javax.swing.JButton();
        jl_Mensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_Año_nac.setFont(new java.awt.Font("Source Sans Pro ExtraLight", 3, 14)); // NOI18N
        jl_Año_nac.setForeground(new java.awt.Color(204, 0, 153));
        jl_Año_nac.setText("Año en que nacio");
        getContentPane().add(jl_Año_nac, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 44, 150, 50));

        jtf_Año_nac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_Año_nacActionPerformed(evt);
            }
        });
        getContentPane().add(jtf_Año_nac, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 54, 109, 33));

        jbtn_Verificar.setText("VERIFICAR");
        jbtn_Verificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_VerificarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_Verificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 177, -1, -1));

        jl_Mensaje.setForeground(new java.awt.Color(0, 204, 0));
        jl_Mensaje.setText("NO CONOSCO TU EDAD");
        getContentPane().add(jl_Mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 160, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_VerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_VerificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_VerificarActionPerformed

    private void jtf_Año_nacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_Año_nacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_Año_nacActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Edad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Edad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Edad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Edad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Edad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jbtn_Verificar;
    public javax.swing.JLabel jl_Año_nac;
    public javax.swing.JLabel jl_Mensaje;
    public javax.swing.JTextField jtf_Año_nac;
    // End of variables declaration//GEN-END:variables
}
